targets:
  $default:
    builders:
      # theme_color_palette|infoGeneratorBuilder:
      #   enabled: true
      #   generate_for:
      #     - lib/src/*
      # theme_color_palette|classExtrasGeneratorBuilder:
      #   enabled: true
      #   generate_for:
      #     - lib/src/*
      theme_color_palette|themeColorPaletteGeneratorBuilder:
        enabled: true
        generate_for:
          - lib/*